# Generated by Django 5.2.15 on 2026-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='images/rice.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
