# Generated by Django 5.2.15 on 2026-07-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.EmailField(default='agristore@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='Agri Store', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(default='9876543210', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=20),
        ),
    ]
